services:
  nest-desktop:
    image: nest/nest-desktop:4.2
    ports:
      - "54286:54286"

  nest-simulator:
    image: nest/nest-simulator:3.8
    environment:
      NEST_CONTAINER_MODE: "nest-server"
    ports:
      - "52425:52425"
    volumes:
      - nestmlmodules:/tmp/nestmlmodules

  nestml:
    image: nest/nest-simulator:3.8
    environment:
      NEST_CONTAINER_MODE: "nestml-server"
      NESTML_SERVER_TIMEOUT: 60
    ports:
      - "52426:52426"
    volumes:
      - nestmlmodules:/tmp/nestmlmodules

volumes:
  nestmlmodules:
