version: "3"

services:
  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-desktop:4.0
    ports:
      - "54286:54286"

  nest-server:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.8
    environment:
      NEST_CONTAINER_MODE: "nest-server"
    ports:
      - "52425:52425"
